def print_df_info(df, name):
    print("#############################################################")
    print(f"                    {name.upper()} DATAFRAME INFO:")
    print("-------------------------------------------------------------")
    print("EXAMPLE OF DATA:")
    print(df.head(5), "\n")
    print("-------------------------------------------------------------")
    print("DATAFRAME INFO:")
    print(df.info(), "\n")
    print("-------------------------------------------------------------")
    print("DATAFRAME DESCRIPTION:")
    print(df.describe(), "\n")
    print("-------------------------------------------------------------")
    print(f"Number of null values: {df.isnull().sum().sum()}", "\n")
    print("#############################################################\n\n\n")
